#  Copyright 2016 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
language: objective-c
osx_image: xcode8
sudo: false
rvm:
    - 2.2.5
env:
  matrix:
      - DESTINATION="OS=8.1,name=iPhone 4s" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL"
      - DESTINATION="OS=8.1,name=iPhone 4s" SDK=iphonesimulator10.0 TYPE="UNIT"
      - DESTINATION="OS=8.1,name=iPhone 5" SDK=iphonesimulator10.0 TYPE="UNIT"
      - DESTINATION="OS=8.2,name=iPhone 5s" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL" FILTER="EarlGreyFunctionalTests/FTRKeyboardKeysTest"
      - DESTINATION="OS=8.3,name=iPhone 6" SDK=iphonesimulator10.0 TYPE="CONTRIB_SWIFT"
      - DESTINATION="OS=8.4,name=iPad Retina" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL" FILTER="EarlGreyFunctionalTests/FTRKeyboardKeysTest"
      - DESTINATION="OS=9.0,name=iPhone 6s Plus" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL"
      - DESTINATION="OS=9.0,name=iPhone 4s" SDK=iphonesimulator10.0 TYPE="CONTRIB_SWIFT"
      - DESTINATION="OS=9.1,name=iPhone 6s" SDK=iphonesimulator10.0 TYPE="UNIT"
      - DESTINATION="OS=9.2,name=iPad Air" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL_SWIFT"
      - DESTINATION="OS=9.3,name=iPhone 6s Plus" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL"
      - DESTINATION="OS=10.0,name=iPhone 7" SDK=iphonesimulator10.0 TYPE="FUNCTIONAL"
      - DESTINATION="OS=10.0,name=iPhone 7 Plus" SDK=iphonesimulator10.0 TYPE="UNIT"
      - TYPE="RUBY"
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
before_script:
  - Scripts/setup-earlgrey.sh
script:
 - Scripts/travis.sh
after_failure:
 - tail -n 200 xcodebuild.log
branches:
  only:
  - master